Allow omitting more config values
tenzir/threatbus pull request #150
Opened 2021-07-19 14:47 UTC by lava

###  :notebook_with_decorative_cover: Description

This PR allows users to omit more config values in the threatbus config.

- Only load configured plugins
- Provide more default values
- Update documentation with default values

###  :memo: Checklist

- [x] All user-facing changes have changelog entries.
- [x] The changes are reflected on [docs.tenzir.com/threatbus](https://docs.tenzir.com/threatbus), if necessary.
- [x] The PR description contains instructions for the reviewer, if necessary.

2021-07-20 10:00 UTC, dominiklohmann requested changes
This appears to work alright for Threat Bus itself, but what about the Threat Bus apps? E.g., there's a separate configuration file for PyVAST Threat Bus at `apps/vast/config.yaml.example`. These should be adapted as well.

2021-07-20 11:18 UTC, lava commented on README.md
> +## Development
I did not see what was specific about it; I follow the same steps for non-plugin threatbus development.

2021-07-20 16:38 UTC, lava commented
@dominiklohmann Regarding the apps, these are technically separate from `threatbus` with their own configs. I've added commits to add default values for all settings in `pyvast-threatbus` and `suricata-threatbus` since these are actively used downstream, but `stix-shifter-threatbus` is more experimental/internal afaik so I'll leave that for a future PR.

2021-07-21 07:48 UTC, dominiklohmann approved these changes
I only tested Threat Bus and PyVAST Threat Bus locally, and they seem to work nicely. The changes to Suricata Threat Bus are similar enough and I trust that you tested them locally.

There's one text reflow issue in the README.

2021-07-21 07:48 UTC, dominiklohmann commented on README.md
> +section on [Installation](#installation) below for more information on how to get there.
This needs text reflow to fit col 80.

2021-07-21 11:58 UTC, merged